image.bbclass: remove MLPREFIX from qemuwrapper-cross
Issue: LIN10-3596

As we've already done for qemuwrapper-cross, use ${MLPREFIX}qemuwrapper-cross
doesn't make sense to the image here, but may cause build errors when
-cpopulate_sdk_ext + multilib:

Exception: FileExistsError: [Errno 17] File exists: '/path/to/sysroots-components/corei7-64/qemuwrapper-cross/sysroot-providers/qemuwrapper-cross' -> '/path/to/work/intel_x86_64-wrsmllib32-linux/lib32-wrlinux-image-glibc-std/1.0-r5/lib32-recipe-sysroot/sysroot-providers/qemuwrapper-cross'

ERROR: lib32-wrlinux-image-glibc-std-1.0-r5 do_prepare_recipe_sysroot: Function failed: extend_recipe_sysroot
ERROR: Logfile of failure stored in: /path/to/work/intel_x86_64-wrsmllib32-linux/lib32-wrlinux-image-glibc-std/1.0-r5/temp/log.do_prepare_recipe_sysroot.63801
ERROR: Task (virtual:multilib:lib32:/path/to/foo-image-bar.bb:do_prepare_recipe_sysroot) failed with exit code '1'

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 2018/03/22

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>