oeqa/sdk/cases/buildgalculator.py: skip if gettext not available
Issue: LIN1018-1289

We need to skip this testcase when gettext is not available. Otherwise,
we will have the following error at configure.

  error: possibly undefined macro: AM_NLS

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 20180516

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>