tzcode: update to 2017c
Issue: LIN10-2310

Update LIC_FILES_CHKSUM since the LICENSE file was reworded to make it
more clear.
See: http://mm.icann.org/pipermail/tz/2017-May/025089.html

Add -DHAVE_SNPRINTF to CFLAGS to fix zdump build error on some
distributions (e.g. Ubuntu 14.04):

zdump.c:803:1: error: static declaration of ‘snprintf’ follows
non-static declaration
|  snprintf(char *s, size_t size, char const *format, ...)
|  ^

See: http://mm.icann.org/pipermail/tz/2017-October/025364.html

Briefly:
  Northern Cyprus switches from +03 to +02/+03 on 2017-10-29.
  Fiji ends DST 2018-01-14, not 2018-01-21.
  Namibia switches from +01/+02 to +02 on 2018-04-01.
  Sudan switches from +03 to +02 on 2017-11-01.
  Tonga likely switches from +13/+14 to +13 on 2017-11-05.
  Turks & Caicos switches from -04 to -05/-04 on 2018-11-04.
  A new file tzdata.zi now holds a small text copy of all data.
  The zic input format has been regularized slightly.

(LOCAL REV: NOT UPSTREAM) -- will send to oe-core on 20171026

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>