Revert "image_types_wic.bbclass: Ensure '-c image_wic' works"
Issue: LIN10-3898

This reverts commit 6c32803432cd847ae81767afcfbe4b5db41b9672.

The commit was cherrypicked from rocko, but introduced various multilib
build regressions:

lib32-wrlinux-image-glibc-std-1.0-r5 do_image_wic: lib32-gcc-cross-arm not found
...
ERROR: lib32-wrlinux-image-glibc-std-1.0-r5 do_image_wic: Function failed: extend_recipe_sysroot

Also, after performing some tests, the issue that the commit fixes (build
failure with -c image_wic) seems not to be present in LTS17.

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>