linux-fimware: Remove the new added firmware packages
Issue: LINPUL8-813

Previously these firmware files were included in the linux-firmware
rpm. But when we update linux-firmware_git.bb, some new packages names
are introduced. This is fine when we create a rootfs image. But it will
cause the follow errors when doing rpm update:
  error: file /lib/firmware/i915/bxt_dmc_ver1.bin from install of linux-firmware-0.0+git0+bf04291309-r0.all conflicts with file from package linux-firmware-bxt-
  dmc-ver1-0.0+git0+bfeee58b50-r0.0.all

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>