Revert "oeqa/sdkext/devtool.py: remove workspace/sources before running test cases"
Issue: LIN10-2116

This reverts commit 5f0e6adf40091b3161ec6ea2175b93b3438075d0.

It is not needed any more, and caused error:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/1.0-r1/testsdkext/workspace/sources/v4l2loopback-driver'

(LOCAL REV: NOT UPSTREAM) -- Revert a local patch

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>