openssh: check for OpenSSL with EVP_des_ede3_cbc
While compiling openssl with option `no-des', it caused the openssh
build failure
...
cipher.c:85:41: error: 'EVP_des_ede3_cbc' undeclared here (not in a function);
...

Check for OpenSSL with EVP_des_ede3_cbc

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 20180418

Issue: LIN1018-462

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>